inverter_url = "http://<inverter.ip>/measurements.xml"
poll_interval_secs = 1
max_errors = 40
quiet_mode = true

[mqtt]
broker = "<mqtt.brocker.ip>"
port = 1883
client_id = "inverter_client"

[influxdb]
url = "http://localhost:8086"
token = "your-token-here"
org = "your-org"
bucket = "solar_data"
